### PR TITLE
Wifi refresh

### LINKED ISSUE #32: Refresh wifi list button
##### Expected Behavior
IIt would be nice to have a button to immediately refresh the wifi list of connections.

##### Current Behavior
At the moment, after powering on my router, I have to wait until nm-tray decides to refresh the list (don't know how often it happens, but surely it's not immediate).

##### Possible Solution
It would be nice to have a "Refresh list" button in the context menu which automatically refresh the list of available wifi connection.

### PR DESCRIPTION
**Pull request by palinek**
fixes #32

### CODE REVIEW

**Comment by tigerjack** [comment]
Hey palinek, thanks for the fast response. I'll check it once it will be available on the arch linux AUR. Are you the maintainer of the package?

**Comment by palinek** [comment]
> Are you the maintainer of the package?

No. I'm not.

> I'll check it once it will be available on the arch linux AUR.

It probably will not get there until the PR is merged into master. And that will probably not happen until you (someone else?) confirm the PR :)

**Comment by tigerjack** [comment]
Ok, I tested it and it seems to work seamlessly, also avoiding scans when there have been previous scans 

`nm-tray: requestScan on device 'wlp3s0' failed: Scanning not allowed immediately following previous scan`

However, I get a a couple of this strange message, not sure if strictly related to this version

```
nm-tray: deactivateConnection "/org/freedesktop/NetworkManager/ActiveConnection/3"
nm-tray: void NmModelPrivate::onActiveConnectionRemoved(const QString&) /org/freedesktop/NetworkManager/ActiveConnection/3  is currently invalid...
```

**Comment by palinek** [comment]
> However, I get a a couple of this strange message, not sure if strictly related to this version

These are debug messages (which are default off in "Release" builds).

**Comment by tigerjack** [comment]
Ok, so they are harmless, right? So it seems to work :)

**Comment by palinek** [comment]
thanks for review (and an easy feature request)

**Pull request merged**
